# Site Information
title: 'Documentation Name'
tagline: 'Documneantion tagline goes here'
favicon: 'img/logo-light.svg'

# URLs and Deployment
url: 'https://example.com'
baseUrl: '/'

# GitHub pages deployment config
organizationName: 'org name'
projectName: 'project name'

# Error handling
onBrokenLinks: 'throw'
onBrokenMarkdownLinks: 'warn'

# Internationalization
i18n:
  defaultLocale: 'en'
  locales: ['en']