# Documentation Plugins Configuration
plugins:
  - id: 'component-usage'
    path: 'docs/component-usage'
    routeBasePath: 'component-usage'
    sidebarPath: './sidebars.js'

  - id: 'docusaurus-guide'
    path: 'docs/docusaurus-guide'
    routeBasePath: 'docusaurus-guide'
    sidebarPath: './sidebars.js'

  - id: 'overview'
    path: 'docs/overview'
    routeBasePath: 'overview'
    sidebarPath: './sidebars.js'

  - id: 'platform-overview'
    path: 'docs/platform/platform-overview'
    routeBasePath: 'platform-overview'
    sidebarPath: './sidebars.js'

  - id: 'platform1'
    path: 'docs/platform/platform1'
    routeBasePath: 'platform1'
    sidebarPath: './sidebars.js'

  - id: 'platform2'
    path: 'docs/platform/platform2'
    routeBasePath: 'platform2'
    sidebarPath: './sidebars.js'

  - id: 'platform3'
    path: 'docs/platform/platform3'
    routeBasePath: 'platform3'
    sidebarPath: './sidebars.js'

  - id: 'developers'
    path: 'docs/developers'
    routeBasePath: 'developers'
    sidebarPath: './sidebars.js'

  - id: 'roadmap'
    path: 'docs/roadmap'
    routeBasePath: 'roadmap'
    sidebarPath: './sidebars.js'