# Site Configuration
site:
  name: "My Docs"
  title: "My Documentation"
  description: "Modern documentation built with Astro"

# Page Definitions
pages:
  # Documentation Sections (each is independent in navbar)
  docs:
    base_url: "/docs/final-docs"
    type: docs
    layout: "@docs/doc_style1"
    data: "@data/docs/final_docs"


  layouts:
    base_url: "/docs/layouts"
    type: docs
    layout: "@docs/doc_style1"
    data: "@data/docs/layouts"


  components:
    base_url: "/docs/components"
    type: docs
    layout: "@docs/doc_style1"
    data: "@data/docs/components"

  # Blog
  blog:
    base_url: "/blog"
    type: blog
    layout: "@blog/blog_style1"
    data: "@data/blog"

  # Custom Pages
  home:
    base_url: "/"
    type: custom
    layout: "@custom/home"
    data: "@data/pages/home.yaml"

  about:
    base_url: "/about"
    type: custom
    layout: "@custom/info"
    data: "@data/pages/about.yaml"
